#!/usr/bin/env python
name1 = "Jason Mohabir"
name2 = "Jeremy Mohabir"
name3 = "Jayden Mohabir"
name4 = input("nEnter fourth name:")


print()
print(f"{name1:>30}")
print(f"{name2:>30}")
print(f"{name3:>30}")
print(f"{name4:>30}")
print() 
